name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal -o test-results.xml
    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results
        path: test-results.xml

    - name: Create local manifest file
      run: dotnet new tool-manifest
    - name: Install analyzer
      run: dotnet tool install --add-source source/SemVerAnalyzer/bin/Release SemVerAnalyzer
    - name: Analyze semantic version
      run: dotnet analyze-semver -a source/SemVerAnalyzer/bin/Release/netcoreapp3.1/SemVerAnalyzer.dll -o semver-report.md -c source/SemVerAnalyzer/config.json
  test-results:
    runs-on: ubuntu-latest
    needs: build
    if: success() || failure()
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: '**/*/test-results.xml'